# Generated by Django 5.2.6 on 2025-09-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='token_reto',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='token_verdad',
            field=models.CharField(blank=True, editable=False, max_length=32, unique=True),
        ),
    ]
