# Generated by Django 5.2.6 on 2025-10-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0002_pack_token_reto_pack_token_verdad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
