# Generated by Django 5.2.6 on 2025-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0003_pack_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='token',
            field=models.CharField(db_index=True, editable=False, max_length=32, unique=True),
        ),
    ]
