# Generated by Django 5.2.6 on 2025-10-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0004_alter_pack_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='token_reto',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='token_verdad',
        ),
    ]
