# Generated by Django 5.2.6 on 2025-10-14 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0005_remove_pack_token_reto_remove_pack_token_verdad'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='category',
            field=models.CharField(choices=[('🔥 PICANTE', '🔥 Picante'), ('🎉 FIESTA', '🎉 Fiesta'), ('👪 FAMILIAR', '👪 Familiar'), ('❤️ ROMÁNTICO', '❤️ Romántico'), ('🎲 RANDOM', '🎲 Random')], default='🎲 RANDOM', max_length=12),
        ),
        migrations.AddField(
            model_name='pack',
            name='level',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
