# Generated by Django 5.2.6 on 2025-11-03 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0006_pack_category_pack_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Solo lectura')], default='editor', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='verdadoreto_app.pack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_packs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Colaborador de Pack',
                'verbose_name_plural': 'Colaboradores de Packs',
                'indexes': [models.Index(fields=['pack', 'user'], name='verdadoreto_pack_id_d27efa_idx')],
                'unique_together': {('pack', 'user')},
            },
        ),
    ]
