# Generated by Django 5.2.6 on 2025-11-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0007_packcollaborator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('live', 'En juego'), ('ended', 'Finalizada')], db_index=True, default='lobby', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(default='jitsi', max_length=20)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_video_rooms', to=settings.AUTH_USER_MODEL)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_rooms', to='verdadoreto_app.pack')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.IntegerField(default=0)),
                ('seed', models.CharField(blank=True, max_length=40)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='verdadoreto_app.videoroom')),
            ],
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=60)),
                ('role', models.CharField(choices=[('host', 'Host'), ('player', 'Player')], default='player', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_participations', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='verdadoreto_app.videoroom')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'role'], name='verdadoreto_room_id_d44480_idx')],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
