# Generated by Django 5.2.6 on 2025-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0008_videoroom_gamestate_roomparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoroom',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
