# Generated by Django 5.2.6 on 2026-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdadoreto_app', '0009_videoroom_expires_at_videoroom_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packcollaborator',
            name='role',
            field=models.CharField(choices=[('editor', 'Editor'), ('viewer', 'Lector')], default='editor', max_length=12),
        ),
    ]
