"""
Django settings for verdadoreto project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = os.environ.get("DEBUG", "False").lower() == "true"

SECRET_KEY = os.environ.get("SECRET_KEY", "CHANGE_ME_DEV_ONLY")

ALLOWED_HOSTS = [
    ".onrender.com",              # Render
    "tfg-verdad-reto.onrender.com",
    "verdadreto.onrender.com",
    "verdadreto.es",              # tu dominio (cuando lo conectes)
    "www.verdadreto.es",
    "localhost",
    "127.0.0.1",
]

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://verdadreto.es",
    "https://www.verdadreto.es",
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'verdadoreto_app.apps.VerdadoretoAppConfig',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'verdadoreto_app.middleware.CleanupVideoRoomsMiddleware', # para limpiar salas expiradas automáticamente
]

ROOT_URLCONF = 'verdadoreto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'verdadoreto.wsgi.application'
ASGI_APPLICATION = 'verdadoreto.asgi.application'

# Configuración de Channels
# En local (sin REDIS_URL) usa InMemoryChannelLayer (un único proceso).
# En Render/producción, define la variable de entorno REDIS_URL (p.ej. redis://...).
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DEFAULT_DB_URL = f"sqlite:///{BASE_DIR / 'db.sqlite3'}"

db_url = os.environ.get("DATABASE_URL", DEFAULT_DB_URL)

# Fuerza SSL solo si usamos Postgres en Render
is_postgres = db_url.startswith(("postgres://", "postgresql://"))

DATABASES = {
    "default": dj_database_url.config(
        default=db_url,
        conn_max_age=600,
        ssl_require=is_postgres,   # <- evita 'sslmode' bajo SQLite
    )
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Idioma predeterminado de django
# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]  # para desarrollo

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# configuración de login/logout
LOGIN_REDIRECT_URL = '/'   # redirección tras iniciar sesión
LOGOUT_REDIRECT_URL = '/'            # redirección tras cerrar sesión

# Configuración de Jitsi
JITSI_APP_ID = os.environ.get("JITSI_APP_ID")
JITSI_PRIVATE_KEY = os.environ.get("JITSI_PRIVATE_KEY")
JITSI_KID = os.environ.get("JITSI_KID")

if not DEBUG and (not JITSI_APP_ID or not JITSI_PRIVATE_KEY or not JITSI_KID):
    raise RuntimeError("JITSI_APP_ID, JITSI_PRIVATE_KEY and JITSI_KID are required")